# Git
alias ga='git add'
alias gaa='git add --all'
alias gc='git commit'
alias gca='git commit --amend --no-edit'
alias gcm='git commit --message'
alias gcam='git commit --all --message'
alias gco='git checkout'
alias gd='git diff'
alias gds='git diff --staged'
alias gfp='git fetch && git pull'
alias gl='git log'
alias glo='git log --oneline --all --graph --decorate --color'
alias gp='git push'
alias gpl='git pull'
alias gs='git status'
alias gsta='git stash'
alias gstaa='git stash apply'
alias gstc='git stash clear'
alias gstd='git stash drop'
alias gstl='git stash list'
alias gstp='git stash pop'
alias gsts='git stash show'
alias gstu='git stash push --include-untracked'
alias gsw='git switch'
alias gswc='git switch --create'

# Homebrew
alias bi='brew install'
alias bic='brew install --cask'
alias bif='brew info'
alias bl='brew list'
alias bs='brew search'
alias bu='brew uninstall'
alias buc='brew uninstall --cask'
alias buu='brew update && brew upgrade --no-ask'

# Navigation & shell
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias la='ls -A'
alias ll='ls -lh'
alias lla='ls -lAh'
alias reload='exec zsh'

alias lg='lazygit'

# Claude
alias cc='claude'
